### ISSUE TITLE
Tableau: No Data Layers

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-6#1]
When I tried to follow the tutorial for the first checkpoint, I checked the map options and had no options for data layers with which to create the first map. I made very sure to restrict countries to the US. Has anyone, especially Mac users, run into this problem?

**Comment by BrianNewsom** [comment]
I am currently running into this issue on Windows.  Kind of a big issue.  The available check-boxes do not line up with those in the tutorial either.

**Comment by indiesquidge** [comment]
`Hint: You will need to select “Tableau Classic” map to get Data Layer to work.`

This is a hint that is directly under the first checkpoint in the tutorial we are given to follow. Map > Background Maps > Tableau Classic.

**Comment by BrianNewsom** [comment]
Thanks Austin.  Found this shortly after but didn't say so in this issue.  I appreciate the response.  @cwitty1919 hope you found this too.

**Comment by ghost** [comment]
I did as well. Thanks Austin!
