### ISSUE TITLE
Having Trouble Getting MongoDB to Work

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-6#4]
I downloaded MongoDB and have tried to install it by expanding the the .tgz file. When I try to run the "mongo" command in the terminal, the command is not recognized. I've tried going into the MongoDB file and trying to execute the commands by clicking on them in the bin file, and this is the result:

![image](https://cloud.githubusercontent.com/assets/8551620/4516429/2c1f32aa-4bf6-11e4-8232-0de96931157a.png)

 Also, I have tried installing MongoDB using homebrew, and my terminal has been stuck at this stage for the past 10 minutes:

![image](https://cloud.githubusercontent.com/assets/8551620/4516428/128622fe-4bf6-11e4-8da5-500a95994a31.png)

**Comment by wannabeCitizen** [comment]
Gotta read that documentation.

The startup command for mongo is `mongod`

Also, I'd consider installing w/ Brew:
http://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/

**Comment by alne4294** [comment]
The first issue is because your mongo daemon is not running or has an issue.  Check that mongod is run in the background or from a separate terminal with the command "mongod".

I'm not sure about second issue, but it appears to be a permissions problem.  I would try running as sudo.

**Comment by ghost** [comment]
I can't even run "sudo" with homebrew, but that is a problem I will have to fix later.

Instead, I am running everything manually by specifying the entire path and it seems to work. Thanks for your help.
